name: Deploy Lambda

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ap-northeast-3
  LAMBDA_FUNCTION_NAME: controlBot4EmpyrionServer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install dependencies with uv
      run: |
        # システムレベルの依存関係をインストール
        sudo apt-get update
        sudo apt-get install -y python3-dev build-essential

        # パッケージディレクトリの作成
        mkdir -p package/

        # uvを使用して依存関係をインストール
        uv pip install --system -r requirements.txt --target ./package/

        # ソースコードのコピー
        cp lambda_function.py package/

        # デプロイパッケージの作成
        cd package
        zip -r ../deployment-package.zip .
        cd ..

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --zip-file fileb://deployment-package.zip