name: Deploy Lambda

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ap-northeast-3
  LAMBDA_FUNCTION_NAME: controlBot4EmpyrionServer
  LAYER_NAME: cffi-layer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Create and deploy Lambda Layer
      run: |
        # Layer用のディレクトリ作成
        mkdir -p python/

        # 依存関係のインストール
        pip install \
          PyNaCl==1.5.0 \
          cffi==1.15.1 \
          pycparser==2.21 \
          --platform manylinux2014_x86_64 \
          --implementation cp \
          --python-version 3.9 \
          --only-binary=:all: \
          --target python/

        # Layerのzip作成
        cd python && zip -r ../layer.zip . && cd ..

        # Layerのデプロイ
        LAYER_VERSION=$(aws lambda publish-layer-version \
          --layer-name ${{ env.LAYER_NAME }} \
          --zip-file fileb://layer.zip \
          --compatible-runtimes python3.9 \
          --query 'Version' \
          --output text)

        # Lambda関数にLayerをアタッチ
        aws lambda update-function-configuration \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --layers $(aws lambda list-layer-versions \
            --layer-name ${{ env.LAYER_NAME }} \
            --query 'LayerVersions[0].LayerVersionArn' \
            --output text)

    - name: Deploy Lambda Function
      run: |
        # メインの関数コードのデプロイ
        zip -j function.zip lambda_function.py

        aws lambda update-function-code \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --zip-file fileb://function.zip