name: Deploy Lambda

on:
  push:
    branches: [ main ]  # mainブランチにプッシュされた時に実行

env:
  AWS_REGION: ap-northeast-3  # デプロイするリージョン
  LAMBDA_FUNCTION_NAME: controlBot4EmpyrionServer  # Lambda関数名

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -t ./package/
        cd package
        zip -r ../deployment-package.zip .
        cd ..
        zip -g deployment-package.zip lambda_function.py

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --zip-file fileb://deployment-package.zip
